version: '3.5'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./docker/postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
    environment:
      POSTGRES_DB: order_book
      POSTGRES_USER: order_book
      POSTGRES_PASSWORD: R0aNd54MpA99W0Rd
    ports:
      - 5432:5432
